builders:
  testApt:
    import: "package:hotfix/builder/apt_builder.dart" #导入工厂方法所在文件
    builder_factories: [ "testApt" ]
    build_extensions: { '.dart': [ '.g.dart' ] }
    build_to: source
    auto_apply: root_package